// Editorial summaries of the authors' public descriptions, not independent product tests.
export const descriptions = {
  'Stxqq/self-driving-car': 'Watch simulated cars learn to steer through highway traffic. A browser experiment for exploring how AI learns to drive.',
  'vedantdhande04/tweetytweets': 'A tool that researches topics, drafts posts, and publishes them to X through a browser for an AI assistant.',
  'facebookresearch/swe-sweep': 'A research project testing how well AI can find and fix bugs in large software projects.',
  'xop01/ai_goodpractice': 'A guide to using AI in everyday work, with advice for beginners and experienced users.',
  'chen-006/meow-ai-arena': 'Watch AI models compete in territory games, Bomberman, and capture the flag. Includes game rules, replays, results, and code to run challenges.',
  'chenjin-cmd/wechat-graphic-monetization': 'The author has not supplied a useful description yet. Read the project documentation before deciding whether to try it.',
  'ZiZc3/XPSemu': 'An experimental version of an original Xbox emulator adapted for PlayStation 5.',
  'Roylyl/WinPlay': 'Show and control your iPhone’s CarPlay screen on a Windows computer over Wi-Fi or a local network.',
  'SHORiN-KiWATA/linuxqq-wayland-fix': 'Fix screen sharing, screenshots, and clipboard problems in the Linux version of QQ when using a Wayland desktop.',
  'saawant12/orbit-store-ps5': 'Manage downloads on a PlayStation 5, resume interrupted downloads, and control them from your phone.',
  'real-simple-labs/ai-creative-strategist-blueprint-ii': 'A collection of class recordings, transcripts, slides, and resources about using AI for creative strategy.',
  'Tuskira/ai-agent-gateway': 'A control point for monitoring and restricting the tools and AI services that automated assistants can use.',
  'DozenTwelve/Papermorph': 'Instructions for an AI assistant to turn books into interactive web experiences with animation and narration.',
  'flaviocopes/factorylog': 'See a daily and weekly timeline of work done by your AI coding assistants on a Mac, organized by project.',
  'Itz-Anya/Image-Size-Reducer': 'Make image files smaller in your browser, with controls for picture quality and output settings.',
  'hugelton/Felucca': 'Replacement software for an M-VAVE FM-1 device. You need the matching hardware to use it.',
  'unclejobs-ai/motion-video-skill': 'A set of instructions and step-by-step checks that helps Claude Code create motion graphics and videos.',
  'Zhou-Yujing114514/deepseek-harness-linux': 'Linux installation packages for the DeepSeek Harness desktop application, covering common computer processors.',
  'Soulringen/aegis-claude': 'A Windows tool that resets local Claude device identifiers. The author says it preserves chat history.',
  'Sleepy-Avacado/FigGenie-paper-diagram-skill': 'Help an AI assistant create diagrams for research papers, with editable PowerPoint, SVG, and PDF output.',
  'bangtutorial/bang-story': 'A desktop app that uses AI to turn a story idea into a script, pictures, and a YouTube video.',
  'feiyuaq/zcfsrf': 'A typing tool designed to help you learn English while you type.',
  'ZeldaWWHDRecomp/ZeldaWWHDRecomp': 'A project to rebuild Zelda: The Wind Waker HD for other systems. Check its documentation for game-file and hardware requirements.',
  'kindlingai/kindling-spark-os': 'A small operating-system image for NVIDIA DGX Spark and ASUS GX10 computers, designed with a read-only system.',
  'QuartzCabinDawn/DiscordFix-Setup': 'Settings and configuration files intended to fix Discord connection and access problems on Windows 10 and 11.',
  'nailuj05/framemate': 'A companion app for Steam Frame. The short author description does not explain its specific features yet.',
  'heise3/academic-deai': 'Editing guidance for Chinese and English academic writing, intended to make wording less formulaic while preserving evidence and citations.',
  'mkdir700/wx-ime-sdk': 'A developer tool for accessing WeType’s clipboard sharing between devices without using its full typing app.',
  'Dominic-DK/harness-map': 'See a visual map of the instructions, memory, tools, and permissions assembled for Claude Code in different folders.',
  'henrydennis/petal': 'Find out what is taking up space on your Mac with an interactive disk-usage chart.',
  'jarrodwatts/intermission': 'Play multiplayer Doom while Claude Code works on a task. Installed as a Claude Code plugin.',
  'Jakeschincariol/replica-skill': 'Eleven sets of instructions for Claude to study an application, rebuild its behavior, test it, and improve it.',
  'OpenCourant/OpenCourant': 'Engineering simulation software for studying crashes, impacts, explosions, and how materials respond.',
  'gillesgoetsch/omacvm': 'Run the Omarchy Linux desktop inside a virtual computer on your Mac, with Mac-style scrolling and trackpad controls.',
  'zoolapp/aime': 'An open-source Chinese typing app for macOS that works locally and offers optional AI features.',
  'jarrodwatts/claude-image-view': 'Show image thumbnails when you paste pictures into Claude Code, making it easier to see what you attached.',
  'egmalt/house-planner': 'Draw a house in 2D and 3D, plan utilities, and estimate materials. Intended to run on your own hosting.',
  'ACoci86/terrahour': 'A world clock for your computer’s text terminal that helps find meeting times across time zones.',
  'telepath-computer/television': 'A visual workspace where you and an AI assistant can create and work with files and other outputs.',
  'lxj5820/dsh-boot-animation': 'Replace a DSH app’s startup screen with a full-window video that fades into the application.',
  'adityajha2005/yc-outreach': 'Find founders from a Y Combinator group and draft personalized outreach emails from a template.',
  'Remocn/remocn-studio': 'A video editor designed to be operated by AI assistants. The author’s short description does not list detailed features.',
  'KODAMA-TECHNOLOGY/Chat_UI': 'A very small chat interface for talking with AI models, built without extra software dependencies.',
  'rbrown101010/bluey-by-riley': 'A playful blueberry character on your iPhone that can point at and interact with your Mac through companion apps.',
  'zzzz7788990213-ops/EvoVLM': 'AI research software that searches for better ways to process images and language together.',
  'Kutuyyy/Leaked-System-Prompt-AI': 'A collection claiming to document the hidden instructions used by popular AI products. Those claims are not verified here.',
  'luki-1/ArkWeb': 'An experimental game modification bringing Spider-Man-style web swinging to Batman: Arkham Knight.',
  'NuvexNetwork/nuvex-web': 'The informational website for Nuvex, a blockchain computing project. This website does not make transactions.',
  'idlerunner00/procedural-pixel-creatures': 'Generate pixel-art creatures automatically inside the Godot game editor.',
  'NuvexNetwork/nuvex': 'Developer infrastructure for Solana applications to request calculations and verifiable random numbers.',
  'NuvexNetwork/nuvex-docs': 'Documentation explaining the Nuvex blockchain computing project.',
  'mizorewww/x_gift_bot': 'A command-line tool and website for handling X Premium gifts and their redemption.',
  'BootLoops-ai/bootloops': 'Precise calculation tools for physics and scientific work, designed to be used by AI assistants.',
  'StayLameBro/backburner': 'Use an iPhone connected by USB-C to help a Mac process a large AI language model.',
  'whirlchat/whirl': 'An AI chat application combining multiple models, saved memory, documents, and custom tools.',
  'youcci/playport': 'Display wireless CarPlay in a web browser on a screen connected to your network. Requires receiver software running on another machine.',
  'QingYunA/answer-me-with-html': 'Instructions that help an AI assistant explain a complicated question as an easy-to-read web page.',
  'sganggs/Stronghold-Protocol': 'An unofficial, noncommercial Arknights fan game combining automatic battles and tower defense in a browser, alone or with up to four players.',
  'facebookincubator/muse-gadget-sdk': 'Developer tools for building Muse gadgets. This is a toolkit for programmers rather than a finished consumer app.',
};
